import { Alert, Box, Button, Card, CardContent, Dialog, DialogActions, DialogContent, DialogTitle, Grid, IconButton, MenuItem, Stack, TextField } from '@mui/material';
import { FiEdit2, FiPlus, FiTrash2 } from 'react-icons/fi';
import { useEffect, useState } from 'react';
import { PageHeader } from '../../components/common/PageHeader';
import { DataTable } from '../../components/common/DataTable';
import { StatusBadge } from '../../components/common/StatusBadge';
import { workOrderService } from '../../services/workOrderService';
import { customerService } from '../../services/customerService';
import { siteService } from '../../services/siteService';
import { technicianService } from '../../services/technicianService';
import type { CreateWorkOrderRequest, Customer, Site, Technician, UpdateWorkOrderRequest, WorkOrder } from '../../types';

const empty:CreateWorkOrderRequest={workOrderNumber:'',customerId:'',siteId:'',technicianId:'',title:'',description:'',priority:'MEDIUM',status:'NEW',scheduledDate:''};
const statuses=['NEW','ASSIGNED','IN PROGRESS','ON HOLD','COMPLETED','CLOSED']; const priorities=['LOW','MEDIUM','HIGH','CRITICAL'];
const toInput=(value?:string)=>value?value.slice(0,16):'';
export const WorkOrdersPage=()=>{const[rows,setRows]=useState<WorkOrder[]>([]);const[customers,setCustomers]=useState<Customer[]>([]);const[sites,setSites]=useState<Site[]>([]);const[technicians,setTechnicians]=useState<Technician[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[open,setOpen]=useState(false);const[editing,setEditing]=useState<WorkOrder|null>(null);const[form,setForm]=useState<CreateWorkOrderRequest>(empty);
 const load=async()=>{setLoading(true);setError('');try{const[w,c,s,t]=await Promise.all([workOrderService.list(),customerService.list(),siteService.list(),technicianService.list()]);setRows(w.data);setCustomers(c.data);setSites(s.data);setTechnicians(t.data)}catch(e){setError(e instanceof Error?e.message:'Unable to load work orders.')}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const create=()=>{setEditing(null);setForm(empty);setOpen(true)};const edit=(r:WorkOrder)=>{setEditing(r);setForm({workOrderNumber:r.workOrderNumber,customerId:r.customerId,siteId:r.siteId,technicianId:r.technicianId??'',title:r.title,description:r.description??'',priority:r.priority,status:r.status,scheduledDate:toInput(r.scheduledDate)});setOpen(true)};
 const save=async()=>{try{if(editing){const d:UpdateWorkOrderRequest={technicianId:form.technicianId||undefined,title:form.title,description:form.description,priority:form.priority,status:form.status,scheduledDate:form.scheduledDate||undefined,completedDate:form.status==='COMPLETED'?new Date().toISOString():editing.completedDate};await workOrderService.update(editing.id,d)}else await workOrderService.create({...form,technicianId:form.technicianId||undefined,scheduledDate:form.scheduledDate||undefined});setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save work order.')}};
 const remove=async(id:string)=>{if(!window.confirm('Delete this work order?'))return;try{await workOrderService.remove(id);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete work order.')}};
 const customerName=(id:string)=>customers.find(c=>c.id===id)?.companyName??id; const siteName=(id:string)=>sites.find(s=>s.id===id)?.siteName??id; const techName=(id?:string)=>id?technicians.find(t=>t.id===id)?`${technicians.find(t=>t.id===id)?.firstName} ${technicians.find(t=>t.id===id)?.lastName}`:id:'Unassigned';
 return <Box><PageHeader title="Work Orders" subtitle="Create and manage real service work orders" action={<Button variant="contained" startIcon={<FiPlus/>} onClick={create}>Create work order</Button>}/>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Card><CardContent><DataTable rows={rows} loading={loading} emptyMessage="No work orders found" columns={[{key:'workOrderNumber',label:'Number'},{key:'title',label:'Title'},{key:'customerId',label:'Customer',render:r=>customerName(r.customerId)},{key:'siteId',label:'Site',render:r=>siteName(r.siteId)},{key:'technicianId',label:'Technician',render:r=>techName(r.technicianId)},{key:'priority',label:'Priority'},{key:'status',label:'Status',render:r=><StatusBadge label={r.status} color={r.status==='COMPLETED'||r.status==='CLOSED'?'success':r.status==='NEW'?'warning':'primary'}/>},{key:'id',label:'Actions',render:r=><Stack direction="row"><IconButton onClick={()=>edit(r)}><FiEdit2/></IconButton><IconButton color="error" onClick={()=>void remove(r.id)}><FiTrash2/></IconButton></Stack>}]}/></CardContent></Card>
 <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="md"><DialogTitle>{editing?'Edit work order':'Create work order'}</DialogTitle><DialogContent><Grid container spacing={2} sx={{mt:.5}}>{!editing&&<Grid item xs={12} sm={6}><TextField label="Work order number" value={form.workOrderNumber} onChange={e=>setForm(p=>({...p,workOrderNumber:e.target.value}))} fullWidth required/></Grid>}<Grid item xs={12} sm={editing?12:6}><TextField select label="Customer" value={form.customerId} disabled={!!editing} onChange={e=>setForm(p=>({...p,customerId:e.target.value,siteId:''}))} fullWidth required>{customers.map(c=><MenuItem key={c.id} value={c.id}>{c.companyName}</MenuItem>)}</TextField></Grid><Grid item xs={12} sm={6}><TextField select label="Site" value={form.siteId} disabled={!!editing} onChange={e=>setForm(p=>({...p,siteId:e.target.value}))} fullWidth required>{sites.filter(s=>!form.customerId||s.customerId===form.customerId).map(s=><MenuItem key={s.id} value={s.id}>{s.siteName}</MenuItem>)}</TextField></Grid><Grid item xs={12} sm={6}><TextField select label="Technician" value={form.technicianId} onChange={e=>setForm(p=>({...p,technicianId:e.target.value}))} fullWidth><MenuItem value="">Unassigned</MenuItem>{technicians.filter(t=>t.active).map(t=><MenuItem key={t.id} value={t.id}>{t.firstName} {t.lastName}</MenuItem>)}</TextField></Grid><Grid item xs={12} sm={6}><TextField label="Title" value={form.title} onChange={e=>setForm(p=>({...p,title:e.target.value}))} fullWidth required/></Grid><Grid item xs={12}><TextField label="Description" value={form.description} onChange={e=>setForm(p=>({...p,description:e.target.value}))} fullWidth multiline minRows={3}/></Grid><Grid item xs={12} sm={4}><TextField select label="Priority" value={form.priority} onChange={e=>setForm(p=>({...p,priority:e.target.value}))} fullWidth required>{priorities.map(p=><MenuItem key={p} value={p}>{p}</MenuItem>)}</TextField></Grid><Grid item xs={12} sm={4}><TextField select label="Status" value={form.status} onChange={e=>setForm(p=>({...p,status:e.target.value}))} fullWidth required>{statuses.map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField></Grid><Grid item xs={12} sm={4}><TextField label="Scheduled date" type="datetime-local" value={form.scheduledDate??''} onChange={e=>setForm(p=>({...p,scheduledDate:e.target.value}))} fullWidth InputLabelProps={{shrink:true}}/></Grid></Grid></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" onClick={()=>void save()}>{editing?'Save changes':'Create work order'}</Button></DialogActions></Dialog></Box>;
};
