import { Alert, Box, Button, Card, CardContent, Dialog, DialogActions, DialogContent, DialogTitle, Grid, IconButton, MenuItem, Stack, TextField } from '@mui/material';
import { FiEdit2, FiPlus, FiTrash2 } from 'react-icons/fi';
import { useEffect, useState } from 'react';
import { PageHeader } from '../../components/common/PageHeader';
import { DataTable } from '../../components/common/DataTable';
import { StatusBadge } from '../../components/common/StatusBadge';
import { siteService } from '../../services/siteService';
import { customerService } from '../../services/customerService';
import type { CreateSiteRequest, Customer, Site, UpdateSiteRequest } from '../../types';

const empty:CreateSiteRequest={customerId:'',siteCode:'',siteName:'',addressLine1:'',addressLine2:'',city:'',state:'',postalCode:'',country:'',contactPerson:'',phoneNumber:''};
export const SitesPage=()=>{const[rows,setRows]=useState<Site[]>([]);const[customers,setCustomers]=useState<Customer[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[open,setOpen]=useState(false);const[editing,setEditing]=useState<Site|null>(null);const[form,setForm]=useState<CreateSiteRequest>(empty);
 const load=async()=>{setLoading(true);setError('');try{const [s,c]=await Promise.all([siteService.list(),customerService.list()]);setRows(s.data);setCustomers(c.data);}catch(e){setError(e instanceof Error?e.message:'Unable to load sites.');}finally{setLoading(false);}};useEffect(()=>{void load();},[]);
 const create=()=>{setEditing(null);setForm(empty);setOpen(true)};const edit=(r:Site)=>{setEditing(r);setForm({customerId:r.customerId,siteCode:r.siteCode,siteName:r.siteName,addressLine1:r.addressLine1,addressLine2:r.addressLine2??'',city:r.city,state:r.state,postalCode:r.postalCode??'',country:r.country,contactPerson:r.contactPerson??'',phoneNumber:r.phoneNumber??''});setOpen(true)};
 const save=async()=>{try{if(editing){const d:UpdateSiteRequest={siteName:form.siteName,addressLine1:form.addressLine1,addressLine2:form.addressLine2,city:form.city,state:form.state,postalCode:form.postalCode,country:form.country,contactPerson:form.contactPerson,phoneNumber:form.phoneNumber,active:editing.active};await siteService.update(editing.id,d)}else await siteService.create(form);setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save site.')}};
 const remove=async(id:string)=>{if(!window.confirm('Delete this site?'))return;try{await siteService.remove(id);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete site.')}};
 const customerName=(id:string)=>customers.find(c=>c.id===id)?.companyName??id;
 return <Box><PageHeader title="Sites" subtitle="Manage customer service locations" action={<Button variant="contained" startIcon={<FiPlus/>} onClick={create}>Add site</Button>}/>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Card><CardContent><DataTable rows={rows} loading={loading} emptyMessage="No sites found" columns={[{key:'siteCode',label:'Code'},{key:'siteName',label:'Site'},{key:'customerId',label:'Customer',render:r=>customerName(r.customerId)},{key:'city',label:'City'},{key:'active',label:'Status',render:r=><StatusBadge label={r.active?'Active':'Inactive'} color={r.active?'success':'default'}/>},{key:'id',label:'Actions',render:r=><Stack direction="row"><IconButton onClick={()=>edit(r)}><FiEdit2/></IconButton><IconButton color="error" onClick={()=>void remove(r.id)}><FiTrash2/></IconButton></Stack>}]}/></CardContent></Card>
 <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="md"><DialogTitle>{editing?'Edit site':'Add site'}</DialogTitle><DialogContent><Grid container spacing={2} sx={{mt:.5}}><Grid item xs={12}><TextField select label="Customer" value={form.customerId} disabled={!!editing} onChange={e=>setForm(p=>({...p,customerId:e.target.value}))} fullWidth required>{customers.map(c=><MenuItem key={c.id} value={c.id}>{c.companyName} ({c.customerCode})</MenuItem>)}</TextField></Grid>{(['siteCode','siteName','addressLine1','addressLine2','city','state','postalCode','country','contactPerson','phoneNumber'] as const).map(f=><Grid item xs={12} sm={f==='addressLine1'||f==='addressLine2'?12:6} key={f}><TextField label={f.replace(/([A-Z])/g,' $1')} value={form[f]??''} onChange={e=>setForm(p=>({...p,[f]:e.target.value}))} fullWidth required={['siteCode','siteName','addressLine1','city','state','country'].includes(f)}/></Grid>)}</Grid></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" onClick={()=>void save()}>{editing?'Save changes':'Create site'}</Button></DialogActions></Dialog></Box>;
};
