import { Alert, Box, Button, Card, CardContent, Dialog, DialogActions, DialogContent, DialogTitle, Grid, IconButton, Stack, TextField } from '@mui/material';
import { FiEdit2, FiPlus, FiTrash2 } from 'react-icons/fi';
import { useEffect, useState } from 'react';
import { PageHeader } from '../../components/common/PageHeader';
import { DataTable } from '../../components/common/DataTable';
import { StatusBadge } from '../../components/common/StatusBadge';
import { technicianService } from '../../services/technicianService';
import type { CreateTechnicianRequest, Technician, UpdateTechnicianRequest } from '../../types';
const empty:CreateTechnicianRequest={employeeCode:'',firstName:'',lastName:'',email:'',phoneNumber:'',specialization:''};
export const TechniciansPage=()=>{const[rows,setRows]=useState<Technician[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[open,setOpen]=useState(false);const[editing,setEditing]=useState<Technician|null>(null);const[form,setForm]=useState<CreateTechnicianRequest>(empty);
 const load=async()=>{setLoading(true);setError('');try{setRows((await technicianService.list()).data)}catch(e){setError(e instanceof Error?e.message:'Unable to load technicians.')}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const edit=(r:Technician)=>{setEditing(r);setForm({employeeCode:r.employeeCode,firstName:r.firstName,lastName:r.lastName,email:r.email,phoneNumber:r.phoneNumber??'',specialization:r.specialization??''});setOpen(true)};const create=()=>{setEditing(null);setForm(empty);setOpen(true)};
 const save=async()=>{try{if(editing){const d:UpdateTechnicianRequest={firstName:form.firstName,lastName:form.lastName,email:form.email,phoneNumber:form.phoneNumber,specialization:form.specialization,active:editing.active};await technicianService.update(editing.id,d)}else await technicianService.create(form);setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save technician.')}};
 const remove=async(id:string)=>{if(!window.confirm('Delete this technician?'))return;try{await technicianService.remove(id);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete technician.')}};
 return <Box><PageHeader title="Technicians" subtitle="Manage field technicians and their active status" action={<Button variant="contained" startIcon={<FiPlus/>} onClick={create}>Add technician</Button>}/>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Card><CardContent><DataTable rows={rows} loading={loading} emptyMessage="No technicians found" columns={[{key:'employeeCode',label:'Employee code'},{key:'firstName',label:'Name',render:r=>`${r.firstName} ${r.lastName}`},{key:'email',label:'Email'},{key:'specialization',label:'Specialization'},{key:'active',label:'Status',render:r=><StatusBadge label={r.active?'Active':'Inactive'} color={r.active?'success':'default'}/>},{key:'id',label:'Actions',render:r=><Stack direction="row"><IconButton onClick={()=>edit(r)}><FiEdit2/></IconButton><IconButton color="error" onClick={()=>void remove(r.id)}><FiTrash2/></IconButton></Stack>}]}/></CardContent></Card>
 <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>{editing?'Edit technician':'Add technician'}</DialogTitle><DialogContent><Grid container spacing={2} sx={{mt:.5}}>{(['employeeCode','firstName','lastName','email','phoneNumber','specialization'] as const).map(f=><Grid item xs={12} sm={f==='specialization'?12:6} key={f}><TextField label={f.replace(/([A-Z])/g,' $1')} value={form[f]??''} disabled={Boolean(editing&&f==='employeeCode')} onChange={e=>setForm(p=>({...p,[f]:e.target.value}))} fullWidth required={['employeeCode','firstName','lastName','email'].includes(f)}/></Grid>)}</Grid></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" onClick={()=>void save()}>{editing?'Save changes':'Create technician'}</Button></DialogActions></Dialog></Box>;
};
